# 1. tensorflow lecture (ver 2.0)

- 딥러닝의 점유율 90% 이상 
- 난이도가 높은 대신 속도가 더 빠름, 고로 산업계에서 주로 사용 
- computing 자원이 한정적일 경우 훨씬 효율적임

In [23]:
import math 

print(math.pi)
print(math.sin(10))

print(math.ceil(2.5)) # 올림 
print(math.floor(2.5)) # 내림 
print(round(2.6))#반올림 
import math as m 
print(m.pi)

from math import pi, sin 
print(pi)
print(sin(10)) 

3.141592653589793
-0.5440211108893698
3
2
3
3.141592653589793
3.141592653589793
-0.5440211108893698


### cf : 차원
   - 0 : scalar [1] 
   - 1 : vector [1,1]
   - 2 : matrix [[1,1],[1,1]]
   - 3 : 3tensor[[[1,1],[1,1]],[[1,1],[1,1]]]
   - n : N tensor 

### cf : back ground
- floating point가 높을 수록 더 정확한 숫자 가능, 하지만 float64가 float32의 메모리 사용량 두 배 
    - => 연산속도 감소 
- 고로 float32를 사용하는게 딥러닝에서 더 좋음 (연산 속도가 더 빠르기 때문) 

In [12]:
pip install tensorflow

Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np
import tensorflow as tf
print(tf.__version__)

2.11.0


# 2. 텐서(Tensor)의 객체 

- 타입(Type): string, float32, float16, int32, int8 등 
- 형상(shape): 0,1,2차원 등의 데이터 차원
- 축(rank): 차원의 개수 

## 2.1 텐서 차원과 연산

In [11]:
a=tf.constant(2) 
print(tf.rank(a))
print(a)
#tensorflow에 2하나만 들어갔으므로 차원(rank)==0이고 값(print(a))==2 이다. 

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)


In [14]:
b=tf.constant([2,3])
print(tf.rank(b))
print(b)
#tensorflow에 [2,3]의 vector가 들어감. rank==1, 값==[2,3] shape==(2,) <- 1차원 이므로 

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor([2 3], shape=(2,), dtype=int32)


In [5]:
c=tf.constant([[2,3],[6,7]])
print(tf.rank(c))
print(c)
#tensorflow에 [2,3]\n[6,7]의 matrix가 들어감. rank==2, 값==[[2,3],[6,7]], shape==(2,2)

tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(
[[2 3]
 [6 7]], shape=(2, 2), dtype=int32)


### + tensorflow 에 숫자뿐만 아니라 문자도 사용 가능하다. 

In [6]:
d= tf.constant(['hello'])
print(tf.rank(d))
print(d)
# dtype이 int32가 아닌 string임을 볼 수 있음 
# string == vector로 나타남 (1차원 tensor)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor([b'hello'], shape=(1,), dtype=string)


## 2.2 난수 생성

In [11]:
rand1=tf.random.uniform([1],0,1) # 0과 1사이의 uniform distribution에서 shape이 [1]인 애를 sampling하겠다. 
print(rand1.shape)
print(rand1) #dtype이 float이다. 

(1,)
tf.Tensor([0.74167347], shape=(1,), dtype=float32)


In [10]:
rand2=tf.random.normal([1,2],0,1) # 평균이 0, 표준편차가 1인 normal distribution에서 [1,2]의 vector를 가진 애를 sampling을 하겠다. 
print(rand2.shape)
print(rand2)

(1, 2)
tf.Tensor([[0.79073215 0.4686418 ]], shape=(1, 2), dtype=float32)


# BG. 즉시 실행모드 (Eager Mode) 지원 
- 즉시 실행모드를 통해 tensorflow를 python처럼 사용할 수 있음 
- 1.x 버전에서는 '그래프'를 생성하고, 초기화 한 뒤에 세션을 통해 값을 흐르게 하는 작업을 진행해야함

In [12]:
a=tf.constant(3)
b=tf.constant(2)

In [14]:
print(tf.add(a,b)) #tensor ver 1.0
print(a+b) # tensor ver 2.0 , 훨씬 사람이 쓰기 편해짐

tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)


In [16]:
print(a*b)
print(a-b)
print(a%b)
print(a/b)

tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(1.5, shape=(), dtype=float64)


# 3. tensorflow ↔ numpy 변환 
- numpy()
- tf.convet_to_tensor()

### 3.1 tensorlfow → numpy 변환 

In [22]:
# 위에 a,b는 tensorflow 형태임 
c=(a+b).numpy() 
print(c)
print(type(c)) #type이 numpy로 바뀐 것임을 볼 수 있음 

5
<class 'numpy.int32'>


### 3.2 numpy → tensorflow 변환 

In [20]:
c_sqrt=np.sqrt(c,dtype=np.float32)
c_tensor=tf.convert_to_tensor(c_sqrt)

print(c_tensor)
print(type(c_tensor))

tf.Tensor(2.236068, shape=(), dtype=float32)
<class 'tensorflow.python.framework.ops.EagerTensor'>


# 4. tensorflow를 numpy 처럼 사용하기 
- tensorflow를 numpy처럼 활용할 수 있다 

In [26]:
t=tf.constant([[1.0,2.0,3.0],[4.0,5.0,6.0]])
print(t.shape)
print(t.dtype)

(2, 3)
<dtype: 'float32'>


In [28]:
print(t[:,1:])
#row는 모두 가져오고, col은 1행을 제외하고 가져와라

tf.Tensor(
[[2. 3.]
 [5. 6.]], shape=(2, 2), dtype=float32)


In [29]:
t+10
#모든 원소에 10을 더함

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[11., 12., 13.],
       [14., 15., 16.]], dtype=float32)>

In [30]:
tf.square(t)
#모든 원소를 제곱해준다. 

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 1.,  4.,  9.],
       [16., 25., 36.]], dtype=float32)>

In [31]:
t@tf.transpose(t)
#tf.transpose == 열과 행을 바꾸는 것 
#@가 matrix multification을 나타냄 

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[14., 32.],
       [32., 77.]], dtype=float32)>

# 5. 타입 변환
- tensor의 기본 dtype
    - float형 tensor: float32
    - int형 tensor: int32
- 연산시 tensor의 type을 맞춰야 함 
    - float 32 ~ float 32
    - int 32 ~ int 32 
    - float 32 ~ int 32 <- 알맞지 않은 예 
- 타입변환에는 tf.cast() 사용 

In [32]:
a=tf.constant(2)
print(a)
b=tf.constant(2.)
print(b)

tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(2.0, shape=(), dtype=float32)


In [34]:
a+b
# data type이 일치하지 않으므로 error가 발생한다. 

InvalidArgumentError: cannot compute AddV2 as input #1(zero-based) was expected to be a int32 tensor but is a float tensor [Op:AddV2]

In [35]:
tf.constant(2.)+tf.constant(2.,dtype=tf.float64)
#dtype관점에서는 float 32 != float 64

InvalidArgumentError: cannot compute AddV2 as input #1(zero-based) was expected to be a float tensor but is a double tensor [Op:AddV2]

In [38]:
t=tf.constant(2.,dtype=tf.float64)
t2=tf.constant(2.)
a=tf.cast(t2, tf.float64) #tf.cast()를 사용함으로써 float32 → float64로 변환 
t3=t+a
print(t3)
print(type(t3))

tf.Tensor(4.0, shape=(), dtype=float64)
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [40]:
t=tf.constant(2,) #정수, int32
t1=tf.constant(2.) #실수, float32 
t2=tf.cast(t1,tf.int32) # float32 → int32 
a=t2+t
print(a)
print(type(a))

tf.Tensor(4, shape=(), dtype=int32)
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [42]:
t=tf.constant(2,) #정수, int32
t1=tf.constant(2.) #실수, float32 
t2=tf.cast(t,tf.float32) #int32 → float32
a=t2+t1
print(a)
print(type(a)) 

tf.Tensor(4.0, shape=(), dtype=float32)
<class 'tensorflow.python.framework.ops.EagerTensor'>


# 6. AutoGraph (오토그래프) 
### 이건 ver1.0 얘기임으로 단순 cf
- tensorflow가 작업을 좀 더 빠르게 동작하기 위한 방법으로 Graph을 만들어 연산을 진행
- tf.Graph
- 유연성이 있음
    - 모바일 어플리케이션, 임베디드 기기, 백엔드 서버와 같이 python 인터프리터가 없는 환경에서 tensorflow 사용 가능

In [43]:
import timeit

## 6-1. @tf.function
- 자동으로 그래프를 생성 (auto graph)
- 그래프로 변환하여 사용 -> GPU 연산 가능 
- 파이썬으로 구성된 함수를 tensorflow의 그래프 형태로 다루고 싶을 때 사용 가능 
- 원본 함수가 필요하다면 (tf.function).python_function()
- python에 함수정의 def funcion(x): 위에 @tf.function을 써주면 그 자체가 tensorflow의 함수가 된다.

In [46]:
@tf.function
def my_function(x):
    return x**2-10*x+3

print(my_function(2))
print(my_function(tf.constant(2)))
#input값을 tensor로 넣던, int로 넣던지간에 dtype==tensor이고, 값 또한 같은 output이 산출됨을 알 수 있다. 

tf.Tensor(-13, shape=(), dtype=int32)
tf.Tensor(-13, shape=(), dtype=int32)


In [50]:
def my_func(x):
    return x**2-10*x+3

print(my_func(2))
print(my_func(tf.constant(2)))
#보통의 경우, 이와 같이 int로 넣으면 int로 출력 + tensor로 넣으면 tensor로 출력

-13
tf.Tensor(-13, shape=(), dtype=int32)


# 7.  Autograd (자동미분)
- 'tf.GradientTape' API를 사용 
- tf.Variable 같은 일부 입력에 대한 기울기 계산 
    - 기본적으로 한번만 사용됨
- 변수가 포함된 연산만 기록 

In [51]:
#x와 y의 선언방법 
x=tf.Variable(3.)
with tf.GradientTape() as tape:
    y=x**2

In [52]:
print(type(x))
print(type(y))

<class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [53]:
dy_dx=tape.gradient(y,x) #y를 x로 미분 (미분의대상,미분도구)
dy_dx.numpy()

6.0

In [54]:
x2=tf.Variable(4)
dy_dx=tape.gradient(y,x2) #tape.gradient()함수에는 이미 다른 값이 들어가 있으므로 error 발생 
dy_dx.numpy()

#새롭게 또 gradient를 사용하고 싶다면 with tf.GradientTape() as 00 를 사용하여 새로 만들어야 한다. 

RuntimeError: A non-persistent GradientTape can only be used to compute one set of gradients (or jacobians)

In [58]:
x=tf.Variable(2.)
y=tf.Variable(3.)
with tf.GradientTape() as tape_1:
    y_sq=y**2
    z=x**2+tf.stop_gradient(y_sq) #중간에 있는식(y_sq처럼)을 가지고 올 때는 앞에 tf.stop_gradient() 를 사용함 

In [59]:
grad=tape_1.gradient(z,{'x':x, 'y':y}) #목적이 되는 함수 , 도구들 
print('dz/dx: ',grad['x'])
print('dz/dy: ',grad['y'])

dz/dx:  tf.Tensor(4.0, shape=(), dtype=float32)
dz/dy:  None


In [60]:
#Deeplearning에서의 대중적인 목표: weight, biases의 최적화
weights=tf.Variable(tf.random.normal((3,2)), name="weights")
biases=tf.Variable(tf.zeros(2, dtype=tf.float32), name="biases")

x=[[1.,2.,3.]] #x는 보통 input, 1% 2% 3% 여기선 느낌  

with tf.GradientTape(persistent=True) as tape_2:
    y=x@weights+biases
    loss=tf.reduce_mean(y**2)

In [61]:
[dl_dw, dl_db]=tape_2.gradient(loss, [weights, biases])

In [64]:
print(weights.shape)
print(dl_dw.shape)
print(weights)
print(dl_dw) # 보통 이거 두개를 구한다 라고 mind set 

(3, 2)
(3, 2)
<tf.Variable 'weights:0' shape=(3, 2) dtype=float32, numpy=
array([[-0.7125989 ,  1.828609  ],
       [ 0.00339561,  1.0412098 ],
       [-1.4075394 ,  0.5019637 ]], dtype=float32)>
tf.Tensor(
[[ -4.928426    5.4169197]
 [ -9.856852   10.833839 ]
 [-14.785277   16.25076  ]], shape=(3, 2), dtype=float32)


In [65]:
weights2=tf.Variable(tf.random.normal((3,2)),name="weights")
biases2=tf.Variable(tf.zeros(2, dtype=tf.float32), name="biases")

x2=[[4.,5.,6.]]

print(weights2.shape)
print(dl_dw.shape)
print(weights2)
print(dl_dw)

(3, 2)
(3, 2)
<tf.Variable 'weights:0' shape=(3, 2) dtype=float32, numpy=
array([[-3.3774583 ,  2.244045  ],
       [-0.35360655,  0.56721073],
       [-0.49939013,  1.0329618 ]], dtype=float32)>
tf.Tensor(
[[ -4.928426    5.4169197]
 [ -9.856852   10.833839 ]
 [-14.785277   16.25076  ]], shape=(3, 2), dtype=float32)
